### PR TITLE
Added new themes: Renault style with gold font

### PR DESCRIPTION
**Pull request by anton-slim**
My favorite colors when i worked in Renault company, created by myself

### CODE REVIEW

**Comment by lysyi3m** [comment]
Yay! Looks great. One note: let's use start case  for schemes filenames and it's definitions in `README.md` file.

**Comment by anton-slim** [comment]
ok no problem

**Comment by anton-slim** [comment]
done

**Comment by lysyi3m** [comment]
@anton-slim awesome! Thanks for your contribution 🍻

**Comment by anton-slim** [comment]
I love mac os x terminal and glad to share my theme with all.
I forgot one more thing, please merge my last commit.

**Comment by lysyi3m** [comment]
Okay. Done

**Pull request merged**
