### PR TITLE
Add Nova

### PR DESCRIPTION
**Pull request by brennongs**
I don't know how you do your screenshots, but I think your repository of themes is the best I've found, so here's my take on Nova by @travordmiller

### CODE REVIEW

**Comment by lysyi3m** [comment]
Hi, @super-chump! Thank you for your PR!

1. How to take a theme screenshot is described in [README.md](https://github.com/lysyi3m/osx-terminal-themes#generate-theme-preview).

2. Do not commit `.DS_Store` files, please. They're just a macOS stuff to store custom attributes. They should be ignored by `git` via global `.gitignore` file in the real world.

**Comment by super-chump** [comment]
@lysyi3m Sorry about that! Should be good now :)

**Comment by lysyi3m** [comment]
@super-chump oops! One more left 😁  https://github.com/super-chump/osx-terminal-themes/blob/3603a4edcaaecf05cb03404040b20501966f6276/schemes/.DS_Store

**Comment by super-chump** [comment]
@lysyi3m I just need '.DS-Store' in my .gitignore right??

**Comment by brennongs** [comment]
Ok! This should be good! Let me know if there's anything else you need :)

**Comment by lysyi3m** [comment]
Yep, looks great. Thank you 🍻

**Pull request merged**
